### PR TITLE
Added new sorting algorithm - Count sort Algorithm

### PR DESCRIPTION
**Pull request by Shivamyana19**
Added a new sorting algorithm - Count Sort Algorithm

### CODE REVIEW

**Comment by Shivamyana19** [comment]
Kindly let me know , if any changes are needed.
Add it to Hacktoberfest label.

**Comment by Shivamyana19** [comment]
please merge it under hactoberfest 2021 tag as I have participated in it.

**Comment by aabhijeet011** [comment]
well done @Shivamyana19 keep contributing to open source. More you implement by yourself more you will learn.

**Comment by Shivamyana19** [comment]
Thank you @aabhijeet011 
and i am also planning to add more new algorithms.

**Pull request merged**
